import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { Button, Dropdown, Footer, Navbar, Table } from 'flowbite-react'
import { Tooltip } from 'flowbite-react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Navbar
  fluid={true}
  rounded={true}

>
  <Navbar.Brand href="https://carbot.lol">
  🚗🤖&nbsp;
    <span className="self-center whitespace-nowrap text-xl font-semibold dark:text-white">
      carbot
    </span>
  </Navbar.Brand>
  <Navbar.Toggle />
  <Navbar.Collapse>
    <Navbar.Link
      href="/navbars"
      active={true}
    >
      Vehicles
    </Navbar.Link>
    <Navbar.Link href="/navbars">
      Markets
    </Navbar.Link>
    <Navbar.Link href="/navbars">
      Contact
    </Navbar.Link>
  </Navbar.Collapse>
</Navbar>
<div className="flex flex-wrap items-center gap-2 m-5">
  <div>
  <Dropdown
  label="All Vehicles"
 color={"gray"}
  size="xs"
>
  <Dropdown.Item>
    Acura
  </Dropdown.Item>
  <Dropdown.Item>
    Audi
  </Dropdown.Item>
  <Dropdown.Item>
    BMW
  </Dropdown.Item>
  <Dropdown.Item>
    Chevrolet
  </Dropdown.Item>
</Dropdown>
  </div>
  </div>

  <Table hoverable={true}>
  <Table.Head>
    <Table.HeadCell>
      Vehicle
    </Table.HeadCell>
    <Table.HeadCell>
    <Tooltip
  content={<span style={{ textTransform: "none" }}>The median price of the vehicle in the last 90 days.</span>}
  animation="duration-500"
>
      Price
    </Tooltip>
    </Table.HeadCell>
    <Table.HeadCell>
      90d
    </Table.HeadCell>
    <Table.HeadCell>
      365d
    </Table.HeadCell>
    <Table.HeadCell>
    Volume
    </Table.HeadCell>
  </Table.Head>
  <Table.Body className="divide-y">
    <Table.Row className="bg-white dark:border-gray-700 dark:bg-gray-800">
      <Table.Cell className="whitespace-nowrap font-medium text-gray-900 dark:text-white">
        BMW 3-Series (E30)
      </Table.Cell>
      <Table.Cell>
        $10,124.21
      </Table.Cell>
      <Table.Cell>
        14.2%
      </Table.Cell>
      <Table.Cell>
        33.5%
      </Table.Cell>
      <Table.Cell>
       2301
      </Table.Cell>
    </Table.Row>
   
  </Table.Body>
</Table>
<Footer container={true}>
  <div className="w-full text-center">

 
    <Footer.Copyright
      href="#"
      by="carbot"
      year={2023}
    />
  </div>
</Footer>

    </>
  )
}
