import Head from "next/head";
import { Button, Footer, Navbar, Tabs } from "flowbite-react";
import { RefObject, useRef } from "react";
import Breadcrumb from "../components/breadcrumb/Breadcrumb";
import BreadcrumbItem from "../components/breadcrumb/breadcrum-item/BreadcrumItem";



export default function Vehicle() {
  const tabsRef = useRef<RefObject<HTMLDivElement>>(null);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar fluid={true} rounded={true} className="bg-[#F9FAFB]">
        <Navbar.Brand href="https://carbot.lol">
          🚗🤖&nbsp;
          <span className="self-center whitespace-nowrap text-xl font-semibold dark:text-white">
            carbot
          </span>
        </Navbar.Brand>
        <Navbar.Toggle />
        <Navbar.Collapse>
          <Navbar.Link href="/navbars" active={true}>
            Vehicles
          </Navbar.Link>
          <Navbar.Link href="/navbars">Markets</Navbar.Link>
        </Navbar.Collapse>
      </Navbar>
      <div className="flex justify-center ">
        <div className="w-11/12 text-center items-center content-center self-center">
          <div className="mt-7 mb-2">
            <div className="text-left">
          <h1>Porsche 996</h1>
          </div>
            
            
          </div>
        </div>
      </div>
      <Footer container={true}>
        <div className="w-full text-center">
          <Footer.Copyright href="#" by="carbot" year={2023} />
        </div>
      </Footer>
    </>
  );
}
